import React from "react";
import { Icon } from "semantic-ui-react";

export default [
  { key: "phone volume", text: <Icon size="large" name="phone volume" />, value: "phone volume" },
  { key: "universal access", text: <Icon size="large" name="universal access" />, value: "male" },
  { key: "wheelchair", text: <Icon size="large" name="wheelchair" />, value: "wheelchair" },
  { key: "headphones", text: <Icon size="large" name="headphones" />, value: "headphones" },
  { key: "microphone", text: <Icon size="large" name="microphone" />, value: "microphone" },
  { key: "music", text: <Icon size="large" name="music" />, value: "music" },
  { key: "video", text: <Icon size="large" name="video" />, value: "video" },
  { key: "birthday cake", text: <Icon size="large" name="birthday cake" />, value: "birthday cake" },
  { key: "book", text: <Icon size="large" name="book" />, value: "book" },
  { key: "briefcase", text: <Icon size="large" name="briefcase" />, value: "briefcase" },
  { key: "coffee", text: <Icon size="large" name="coffee" />, value: "coffee" },
  { key: "compass outline", text: <Icon size="large" name="compass outline" />, value: "compass outline" },
  { key: "envelope", text: <Icon size="large" name="envelope" />, value: "envelope" },
  { key: "phone", text: <Icon size="large" name="phone" />, value: "phone" },
  { key: "chess", text: <Icon size="large" name="chess" />, value: "chess" },
  { key: "bath", text: <Icon size="large" name="bath" />, value: "bath" },
  { key: "bug", text: <Icon size="large" name="bug" />, value: "bug" },
  { key: "wifi", text: <Icon size="large" name="wifi" />, value: "wifi" },
  { key: "desktop", text: <Icon size="large" name="desktop" />, value: "desktop" },
  { key: "laptop", text: <Icon size="large" name="laptop" />, value: "laptop" },
  { key: "print", text: <Icon size="large" name="print" />, value: "print" },
  { key: "tablet alternate", text: <Icon size="large" name="tablet alternate" />, value: "tablet alternate" },
  { key: "tv", text: <Icon size="large" name="tv" />, value: "tv" },
  { key: "money bill alternate", text: <Icon size="large" name="money bill alternate" />, value: "money bill alternate" },
  { key: "clock outline", text: <Icon size="large" name="clock outline" />, value: "clock outline" },
  { key: "trash alternate", text: <Icon size="large" name="trash alternate" />, value: "trash alternate" },
  { key: "transgender", text: <Icon size="large" name="transgender" />, value: "transgender" },
  { key: "ambulance", text: <Icon size="large" name="ambulance" />, value: "ambulance" },
  { key: "heart", text: <Icon size="large" name="heart" />, value: "heart" },
  { key: "heart outline", text: <Icon size="large" name="heart outline" />, value: "heart outline" },
  { key: "plus square", text: <Icon size="large" name="plus square" />, value: "plus square" },
  { key: "camera", text: <Icon size="large" name="camera" />, value: "camera" },
  { key: "camera retro", text: <Icon size="large" name="camera retro" />, value: "camera retro" },
  { key: "beer", text: <Icon size="large" name="beer" />, value: "beer" },
  { key: "flag", text: <Icon size="large" name="flag" />, value: "flag" },
  { key: "flag outline", text: <Icon size="large" name="flag outline" />, value: "flag outline" },
  { key: "home", text: <Icon size="large" name="home" />, value: "home" },
  { key: "star", text: <Icon size="large" name="star" />, value: "star" },
  { key: "star outline", text: <Icon size="large" name="star outline" />, value: "star outline" },
  { key: "truck", text: <Icon size="large" name="truck" />, value: "truck" },
  { key: "bed", text: <Icon size="large" name="bed" />, value: "bed" },
  { key: "bicycle", text: <Icon size="large" name="bicycle" />, value: "bicycle" },
  { key: "binoculars", text: <Icon size="large" name="binoculars" />, value: "binoculars" },
  { key: "car", text: <Icon size="large" name="car" />, value: "car" },
  { key: "fighter jet", text: <Icon size="large" name="fighter jet" />, value: "fighter jet" },
  { key: "fire extinguisher", text: <Icon size="large" name="fire extinguisher" />, value: "fire extinguisher" },
  { key: "fire", text: <Icon size="large" name="fire" />, value: "fire" },
  { key: "gamepad", text: <Icon size="large" name="gamepad" />, value: "gamepad" },
  { key: "gift", text: <Icon size="large" name="gift" />, value: "gift" },
  { key: "glass martini", text: <Icon size="large" name="glass martini" />, value: "glass martini" },
  { key: "key", text: <Icon size="large" name="key" />, value: "key" },
  { key: "map outline", text: <Icon size="large" name="map outline" />, value: "map outline" },
  { key: "map", text: <Icon size="large" name="map" />, value: "map" },
  { key: "map marker", text: <Icon size="large" name="map marker" />, value: "map marker" },
  { key: "map marker alternate", text: <Icon size="large" name="map marker alternate" />, value: "map marker alternate" },
  { key: "newspaper", text: <Icon size="large" name="newspaper" />, value: "newspaper" },
  { key: "paw", text: <Icon size="large" name="paw" />, value: "paw" },
  { key: "plane", text: <Icon size="large" name="plane" />, value: "plane" },
  { key: "recycle", text: <Icon size="large" name="recycle" />, value: "recycle" },
  { key: "ship", text: <Icon size="large" name="ship" />, value: "ship" },
  { key: "shower", text: <Icon size="large" name="shower" />, value: "shower" },
  { key: "subway", text: <Icon size="large" name="subway" />, value: "subway" },
  { key: "taxi", text: <Icon size="large" name="taxi" />, value: "taxi" },
  { key: "utensils", text: <Icon size="large" name="utensils" />, value: "utensils" },
  { key: "bus", text: <Icon size="large" name="bus" />, value: "bus" },
  { key: "futbol", text: <Icon size="large" name="futbol" />, value: "futbol" },
  { key: "leaf", text: <Icon size="large" name="leaf" />, value: "leaf" },
  { key: "moon", text: <Icon size="large" name="moon" />, value: "moon" },
  { key: "credit card outline", text: <Icon size="large" name="credit card outline" />, value: "credit card outline" },
  { key: "basketball ball", text: <Icon size="large" name="basketball ball" />, value: "basketball ball" },
  { key: "football ball", text: <Icon size="large" name="football ball" />, value: "football ball" },
  { key: "golf ball", text: <Icon size="large" name="golf ball" />, value: "golf ball" },
  { key: "table tennis", text: <Icon size="large" name="table tennis" />, value: "table tennis" },
];
